apiVersion: v1
kind: Pod
metadata:
  name: memory-overuse-pod
  labels:
    name: memory-overuse-pod
spec:
  # selector:
  #   matchLabels:
  #     name: memory-overuse-pod
  containers:
    - name: memory-overuse-container
      image: quay.io/asmacdo/memory-inflation-image:0.0.0
      command:
        - ./memory-inflation
      imagePullPolicy: Always
      ports:
        - containerPort: 3001
