apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-memcached-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: go-memcached-operator
  template:
    metadata:
      labels:
        name: go-memcached-operator
    spec:
      serviceAccountName: go-memcached-operator
      containers:
        - name: go-memcached-operator
          # Replace this with the built image name
          image: quay.io/asmacdo/go-memcached-operator:vblowup2
          # resources:
          #   limits:
          #     memory: "12Mi"
          command:
          - go-memcached-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "go-memcached-operator"
